version: 2.1
executors:
  worker:
    docker:
      - image: panchajanya1999/archlinux:latest
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: Build
          command: |
            wget https://raw.githubusercontent.com/anupamroy777/ci_build-TEMP-/main/build.sh && bash build.sh
